apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: apepipe-expire
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: apepipe-expire
subjects:
  - kind: ServiceAccount
    name: apepipe-expire
    namespace: {{ .Release.Namespace }}
