apiVersion: apps/v1
kind: Deployment
metadata:
  name: apepipe-expire
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: apepipe-expire
  template:
    metadata:
      labels:
        app: apepipe-expire
    spec:
      containers:
        - name: manager
          command: ["/app/manager"]
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
          - name: metric
            containerPort: 8082
            protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8083
            initialDelaySeconds: 15
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8083
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
{{ toYaml .Values.resources | indent 12 }}
          securityContext:
            allowPrivilegeEscalation: false
          {{- if .Values.env }}
          env:
{{ toYaml .Values.env | indent 12 }}
          {{- end }}
      serviceAccountName: apepipe-expire
      securityContext:
        runAsNonRoot: true
      {{- if .Values.tolerations }}
      tolerations:
{{ toYaml .Values.tolerations | indent 8 }}
      {{- end }}
      {{- if .Values.affinity }}
      affinity:
{{ toYaml .Values.affinity | indent 8 }}
      {{- end }}
      imagePullSecrets:
        {{- if .Values.imagePullSecretName }}
        - name: {{ .Values.imagePullSecretName }}
        {{- end }}
        {{- if .Values.dockerconfigjson }}
        - name: apepipe-expire-pull-secret
        {{- end }}
