apiVersion: v1
kind: Service
metadata:
  name: apepipe-expire
  namespace: {{ .Release.Namespace }}
  labels:
    app: apepipe-expire
spec:
  ports:
    - name: metric
      port: 8080
      protocol: TCP
      targetPort: 8082
  selector:
    app: apepipe-expire
